server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: blogmanagement
          uri: http://localhost:8082
          predicates:
            - Path=/blogs/**, /blogReads/**, /blogReadModels/**
        - id: postmanagement
          uri: http://localhost:8083
          predicates:
            - Path=/posts/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: blogmanagement
          uri: http://blogmanagement:8080
          predicates:
            - Path=/blogs/**, 
        - id: postmanagement
          uri: http://postmanagement:8080
          predicates:
            - Path=/posts/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
