---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogmanagement
  labels:
    app: blogmanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blogmanagement
  template:
    metadata:
      labels:
        app: blogmanagement
    spec:
      containers:
        - name: blogmanagement
          image: username/blogmanagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postmanagement
  labels:
    app: postmanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postmanagement
  template:
    metadata:
      labels:
        app: postmanagement
    spec:
      containers:
        - name: postmanagement
          image: username/postmanagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: blogmanagement
  labels:
    app: blogmanagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: blogmanagement


---


apiVersion: v1
kind: Service
metadata:
  name: postmanagement
  labels:
    app: postmanagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: postmanagement

